### ISSUE TITLE
Link to hosted version of Docs in readme instead of the tutorial link.

### ISSUE THREAD

**Issue by maximuskowalski** [alexander0042/pirateweather#1]
Suggest adding a link to the hosted version of docs in the repo readme file instead of linking to the tutorial.

**Comment by alexander0042** [comment]
Great point! I was so focused on getting the "ReadTheDocs" working, I didn't even notice this README. It's been [edited](https://github.com/alexander0042/pirateweather/commit/e9dc6793e54db61a3edf9f57f865ea2160f4243f) to include some basic information and a link to the docs!
