### ISSUE TITLE
Depreciated Forecast

### ISSUE THREAD

**Issue by Necrul** [alexander0042/pirateweather#105]
Got messages in new home assistant update.

This stops working in version 2024.3.0. Please address before upgrading.

The integration pirateweather is using the deprecated forecast attribute.

Please report it to the custom integration author..

Just wanted to bring it to author's attention.

**Comment by cloneofghosts** [comment]
Thank you for reporting the issue. This issue has been reported in the HA repository already here https://github.com/alexander0042/pirate-weather-ha/issues/136 which you can follow to keep up-to-date on any future developments.
