### ISSUE TITLE
API returns incorrect timezone

### ISSUE THREAD

**Issue by jwfox5150** [alexander0042/pirateweather#116]
### Describe the bug

In the response of a lat,long in the Milwaukee Wisconsin area, the response lists timezone as "America/Detroit". All of Wisconsin is "America/Chicago".

?tz=precise returns the correct timezone, however, as this is a pretty cut and dry timezone (body of water in between Wisconsin (CST) and Michigan (EST) I am submitting this in hopes that the rapid timezone can be adjusted.

Example coordinates: 43.04400,-87.8992

### Expected behavior

"timezone": "America/Chicago",

### Actual behavior

"timezone": "America/Detroit",

### API Endpoint

Production

### Location

Milwaukee, WI

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Hi,
Thanks for using this service and opening an issue, and I apologize for this hiccup. This one is a known issue, and comes down to an optimization to improve the performance of the API. Two solutions:

1. In the short term, adding the [`tz=precise` flag](https://pirateweather.net/en/latest/API/#time-zone) tells the service to use the more accurate time zone approach.
2. Version 2.0 has a bunch of more fundamental performance improvements, so I'm hoping to avoid this workaround. I've added this to roadmap for that release!

**Comment by jwfox5150** [comment]
> Hi,
> 
> Thanks for using this service and opening an issue, and I apologize for this hiccup. This one is a known issue, and comes down to an optimization to improve the performance of the API. Two solutions:
> 
> 
> 
> 1. In the short term, adding the [`tz=precise` flag](https://pirateweather.net/en/latest/API/#time-zone) tells the service to use the more accurate time zone approach.
> 
> 2. Version 2.0 has a bunch of more fundamental performance improvements, so I'm hoping to avoid this workaround. I've added this to roadmap for that release! 

Thank you, I appreciate your work on this awesome API! tz=precise is totally fine for my needs in the interim - I haven't really noticed much of a performance difference. Cheers!

**Comment by cloneofghosts** [comment]
Thanks for reporting the issue. I'm going to merge this issue into #104 where you can follow for any future updates on this issue.

**Comment by alexander0042** [comment]
Happy the fix works for now. It's not a massive performance difference (about 0.1s), but on a few million calls a month, it added up to enough to be worth it for most cases
