### ISSUE TITLE
Wrong forecast

### ISSUE THREAD

**Issue by aaruni96** [alexander0042/pirateweather#15]
Since today, the API appears to give the forecast of the wrong location.

My command : 

` curl 'https://dev.pirateweather.net/forecast/<api-key-readacted>/49.4299653,7.7532999?units=si'`

The return begins like :

`{"latitude": 41.198161, "longitude": -73.3492245, "timezone": "America/New_York",`

The returned location is the same, no matter what I query.

**Comment by alexander0042** [comment]
Hi,

Really sorry about this! I was trying to speed up the API response times, so was testing using the gateway cache. However, it seems to have broken everything instead, so definitely not good. It’s been disabled and things should be back to normal.

**Comment by aaruni96** [comment]
Yeah, that fixed it.
