### ISSUE TITLE
Return elevation for requested forecast point

### ISSUE THREAD

**Issue by carloshwa** [alexander0042/pirateweather#2]
Would it be possible to return a field with the elevation for the point that is forecasted? Thanks!

**Comment by alexander0042** [comment]
Sorry I never replied to this! 

Good news here though, as of the latest update, the API now returns elevation data from ETOPO1](https://www.ngdc.noaa.gov/mgg/global/)! I'll update the docs shortly, but let me know if this is what you were looking for.

**Comment by carloshwa** [comment]
That's great, thank you!
