### ISSUE TITLE
Hourly timestamp float

### ISSUE THREAD

**Issue by shawntoffel** [alexander0042/pirateweather#20]
Hello, 

Apologies if I missed this in the documentation. I noticed hourly time has a decimal while others do not. First, is this intended? If so, will the fractional part ever contain a non-zero value? Thank you. 

```json
{
      "time": 1674619200.0,
      "icon": "cloudy",
      "summary": "Cloudy",
      "precipIntensity": 0.0,
      "precipProbability": 0.0,
      "precipIntensityError": 0.0,
      "precipAccumulation": 0.0,
      "precipType": "none",
      "temperature": 32.52,
      "apparentTemperature": 27.42,
      "dewPoint": 29.37,
      "humidity": 0.81,
      "pressure": 1025.9,
      "windSpeed": 5.26,
      "windGust": 12.57,
      "windBearing": 259.29,
      "cloudCover": 1.0,
      "uvIndex": 0.0,
      "visibility": 10.0,
      "ozone": 311.93
}
```

**Comment by alexander0042** [comment]
Good catch- missed the `int` declaration on that one.

I've pushed version 1.3.1 which should correct this. It's live now, so should be corrected now.

Thanks again for taking the time to open an issue here!

**Comment by shawntoffel** [comment]
Wow, that was fast! I verified the fix is in place. Thanks!

**Comment by alexander0042** [comment]
I can't promise I'll always reply this fast, but I happened to have everything open to quickly put this one in! 
Thanks for closing the issue, and let me know if anything else crops up here
