### ISSUE TITLE
HRRR Data Not Integrating

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#22]
I noticed this yesterday on the dev API endpoint but it wasn't an issue until now on the production API. It looks like HRRR data isn't being integrated into the API and it's using the global GFS/GEFS API.

It must be an issue on PirateWeather's end as I see the 16z run of the model on AWS so there should be HRRR data integrated from a previous run being used still.

**Comment by alexander0042** [comment]
Oh shoot- good catch here. I was trying to fix a different issue with the grid referencing, but didn't realize it broke this! I'll fix it and push out a new version stat

**Comment by alexander0042** [comment]
Ok, v1.3.2 is live! I'm updating the change log now, but the deeply uninteresting issue was that I had the x and y variables reversed, so HRRR threw an issue, which excluded it. So silver lining is that the error checking works I suppose.

Thanks again for bringing this to my attention so quickly!

**Comment by cloneofghosts** [comment]
I see the new version and HRRR data is back so I'm going to close this issue. You should probably check the sources section before you push to live to make sure all the sources are there so this isn't repeated.

**Comment by cloneofghosts** [comment]
@alexander0042 With the 1.5.1 update it shows HRRR as a source but it isn't listed in the `sourceTimes` block.

```
  "flags": {
    "sources": [
      "ETOPO1",
      "gfs",
      "gefs",
      "hrrr"
    ],
    "sourceTimes": {
      "hrrr_18-48": "2023-05-27 12:00:00",
      "gfs": "2023-05-27 06:00:00",
      "gefs": "2023-05-27 06:00:00"
    },
    "nearest-station": 0,
    "units": "ca",
    "version": "V1.5.1"
  }
  ```

I don't think the currently section is using HRRR data as when I compare the current temp with the first hourly temp it is much lower

```
  "currently": {
    "time": 1685204220,
    "temperature": 21.53,
  },
    "hourly": {
    "data": [
      {
        "time": 1685203200,
        "temperature": 23.66,
      },

**Comment by alexander0042** [comment]
Good catch here, and unsurprisingly, same underlying issue as the last time. I was working on returning the lat long of the grid point that the model data came from, but ended up breaking it in a weird way that I didn't notice. 

I've corrected it in a v1.5.2, so should be good now!

**Comment by cloneofghosts** [comment]
Can confirm that it's fixed. Thanks.

**Comment by cloneofghosts** [comment]
@alexander0042 Don't forget to update the changelog for the newest versions since it's still only showing up to 1.5.
