### ISSUE TITLE
Precipitation Sensor for actual daily forecast?

### ISSUE THREAD

**Issue by cbp0616** [alexander0042/pirateweather#26]
Looking at both the Daily and Hourly editions of the API, there are several precipitation sensor entities that are added.  However, there is no clear cut one that shows the forecasted daily precipitation like how Dark Sky showed.  Each precipitation sensor reports totally different data which I assume is based on some rolling time line, whether it be an hour, a 24 hr period, etc.  I just want to know which entity I need to use to show the day's forecasted precip amount.  Everything I try doesn't merry up with local forecasts or even MerrySky.

I'd assume " Daily Max Precip Intensity 0d" entity is the one; however, it's report data isn't lining up.

**Comment by cloneofghosts** [comment]
The sensor that you are looking for is the Precipitation Accumulation 0d sensor. That sensor will give you the total accumulation forecasted for the current day in millimeters or inches depending on the units. The Maximum Precip Intensity 0d is just telling you how heavy the precipitation will get during the day.

MerrySky also caches their forecasts and I think they go through the hourly forecast and sum up the precipitation accumulation for each precipitation type so it might not match up with the daily one provided in the sensors.

This looks to be a question for the Home Assistant integration so in the future if you have any questions you should create an issue in the HA repo: https://github.com/alexander0042/pirate-weather-ha

**Comment by cbp0616** [comment]
Thank you for the quick and detailed response and for pointing me to the correction location for future issues.  Awesome work on this project.

**Comment by alexander0042** [comment]
@cloneofghosts, don't sell yourself short, you also reply to these sorts of questions, which I really appreciate! One thing I'm curious about is what the names were in Dark Sky? I've been trying to keep them consistent, and easy to fix naming if something is off

**Comment by cloneofghosts** [comment]
@alexander0042 I'm assuming you're talking about the integration here? I never used it but I think I still have my API key kicking around that I could send for you to check and make sure the names are the same if you'd like (if you don't have your own API key already)
