### ISSUE TITLE
JSON value for "nearest-station" : 0 ??

### ISSUE THREAD

**Issue by ktrue** [alexander0042/pirateweather#28]
In the JSON for the API, the "nearest-station" value seems to be always set to zero.  Is this just because the value is not being currently calculated, so defaults to zero?  If so, is it possible to set the value with respect to the station providing the "currently" value set?

**Comment by cloneofghosts** [comment]
At the moment PirateWeather only integrates model data and does not use station data in the API which is why that value is always zero.

I do not see anything in the road map that station data will be added in the future and I'm not sure how difficult it would be for @alexander0042 to integrate.

**Comment by alexander0042** [comment]
Thanks @cloneofghosts for the quick reply here! You also nailed the answer- the API currently uses gridded model results, so there aren't any "station", per se. It's something that I've been thinking about including, but not presently on the roadmap, so not in the immediate future.
