### ISSUE TITLE
Different results compared to Merry Sky

### ISSUE THREAD

**Issue by crshray** [alexander0042/pirateweather#30]
Hi, I'm seeing different results in home assistant compared to Merry Sky despite using the same GPS coordinate. It's currently snowing in my area, but the home assistant integration shows it's cloudy/fog:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/7625504/224455494-842d6296-5106-4c9c-b552-40a76ff82846.png">

Merrysky with the same GPS coordinate correctly shows snow (https://merrysky.net/forecast/43.84239530,-79.4681130/ca):
<img width="871" alt="image" src="https://user-images.githubusercontent.com/7625504/224455538-0f8ff65c-dd73-4079-a96a-08f86f5894db.png">

**Comment by alexander0042** [comment]
Thanks for bringing this to my attention! It was a rounding issue that was introduced in 1.4. but is fixed now. Apologies for the hiccup here, and let me know if anything else comes up.

**Comment by cloneofghosts** [comment]
It also could be possible that HRRR was reporting no precipitation which can happen sometimes even when it's snowing/raining.
