### ISSUE TITLE
Data not available & questions

### ISSUE THREAD

**Issue by MichaelHopwood** [alexander0042/pirateweather#31]
Thanks for releasing this! It's awesome!
Interestingly, I am running into an issue when querying data on June 30, 2022.

```
POST https://timemachine.pirateweather.net/forecast/[key]/28.92942579,-82.33328679,1656561600?&units=ca&exclude=currently,minutely,daily,alerts
>>
"Data for this date is not yet available, please try an earlier or later date"
```

```
POST https://api.pirateweather.net/forecast/[key]/28.92942579,-82.33328679,1656561600?&units=ca&exclude=currently,minutely,daily,alerts
>>
"Requested time too early, please use https://timemachine.pirateweather.net"
```

A few questions:

1. What is the rule of thumb for which `api` or `timemachine` should be used for a certain time span? Forecasts are in `api` and historical in `timemachine`?
2. Is there a better way of getting historical data for multiple years? I've been querying iteratively each unix date, but was wondering if there's a more efficient way as it takes hours for each lat/lon and takes up a lot of requests.

**Comment by caseyjhol** [comment]
See https://github.com/alexander0042/pirateweather/issues/18#issuecomment-1457630543

**Comment by alexander0042** [comment]
Great questions, and both things I'm working on improving in the documentation. I totally get that it's kind of irritating how there are two different API endpoints, one for future/ near past requests and one for historic ones- it comes down to not having enough space in the Lambda layers for both Zarr and NetCDF files. I could get around this now using Docker containers, but that's a pretty significant undertaking.

To answer your questions:
1. `api` is for anything within the last 5 days, and comes from archived 0-hour forecast data. `timemachine` is for anything ~1.5 months and older, and comes from the ERA5 reanalysis. The gap in the middle is another issue, and something I'm working on addressing with a longer forecast archival time, but I need to figure out a way to keep the files smaller so the storage costs don't get crazy. 
2. Unfortunately, this one isn't possible. The way I read the data from the underlying model only lets me read one day at a time, so I'm limited to the individual request.
