### ISSUE TITLE
Wind degrees precision / DarkSky compatibility

### ISSUE THREAD

**Issue by oisact** [alexander0042/pirateweather#36]
Minor issue here which did cause me issues in my iOS app. DarkSky API reported current wind direction (`windDegrees`) in whole integers. However your PirateWeather API is reporting `windDegrees` as a float with tenth of a degree precision. Tenth of a degree is surely far more precise than the actual accuracy of the data. I'm working around this server-side in my data processing to round it to an integer before my iOS app consumes it. This kind of issue can be common in very type-strict languages like Swift.

Just pointing this out if you are interested in the highest level compatibility with DarkSky.

**Comment by cloneofghosts** [comment]
I know there was talk about having an option to have the API round certain parameters but it never really went anywhere https://github.com/alexander0042/pirate-weather-ha/issues/29.

I definitely like having the extra precision that two decimal points give so maybe having a option to round certain parameters to whole numbers or maybe having a `windBearingCardinal` which displays the cardinal direction would also work?

**Comment by oisact** [comment]
> I definitely like having the extra precision that two decimal points

My point is the underlying model and data are not accurate to that precision, so it's basically random noise / false data anything more accurate than a degree. To give an idea, both NOAA and the FAA require anemometers to be within 5 degrees accuracy. And that is for actual measurements! So having two decimals just means you have two orders of magnitude of precision that doesn't actually exist.

**Comment by cloneofghosts** [comment]
Friendly reminder to look into this issue and other rounding issues that are in issue #4

**Comment by alexander0042** [comment]
Ok, I think I've fixed all the rounding issues! To summarize:

- Precipitation intensity and accumulation are rounded to 4 digits 
- Wind bearing is to the nearest whole number
- Everything else should be two digits

Let me know if notice any glitches, or if anything else should be different. This should also address #4 and #77

**Comment by cloneofghosts** [comment]
@alexander0042 I think their intent was to have `windBearing` have no decimal places where currently it is rounded to the nearest whole number but still has a decimal place `"windBearing": 80.0,`.

`windSpeed` is still rounded to 3 decimal places on currently `"windSpeed": 18.274,` and precipProbibility` seems broken in the minutely section:

```
"data": [
      {
        "time": 1689258960,
        "precipIntensity": 0.0,
        "precipProbability": 2,
        "precipIntensityError": 0.5,
        "precipType": "none"
      },
```

**Comment by alexander0042** [comment]
You have an amazing eye for this stuff! Fixed , fixed, and fixed!

**Comment by cloneofghosts** [comment]
Everything looks good now. Feel free to close.

**Comment by alexander0042** [comment]
Awesome! Each little fix makes this better, step by step
