### ISSUE TITLE
cloudCover inaccurate

### ISSUE THREAD

**Issue by wtluke** [alexander0042/pirateweather#38]
Loving the work @alexander0042 - great service. I had one oddity lately: cloudCover in `currently` seems to flip from `0` to `1` randomly, and any number in between. This is for SE England, a country which spends most of its time under cloud. At the time, it was cloudy, probably near 80% coverage, but the API said `0`. An hour later it flipped to `1`. It's now `0.93`, which seems accurate, but there's little confidence given the number seems to change so often. Is that a bug or an error from whoever you're scraping?

Lastly, how often does this figure update in `currently`?

**Comment by cloneofghosts** [comment]
Your location the API uses GFS/GEFS global models which update every six hours with the last run time being displayed in the flags section and isn't high resolution. The plan is to replace those models with the NBM model which should help improve things.

Similar issues have been posted before and is something that is on the roadmap to be implemented but there is no ETA on when it will be added. https://github.com/alexander0042/pirate-weather-ha/issues/64, https://github.com/alexander0042/pirate-weather-ha/issues/50 and https://github.com/alexander0042/pirate-weather-ha/issues/30

For your other question `cloudCover` is updated once per hour usually at around 30 minutes past the hour.

**Comment by cloneofghosts** [comment]
@alexander0042 Do you think adding in RAP data would be a good temporary solution until NBM gets integrated? From what I see RAP is pretty much just HRRR on a larger scale which includes parts of Europe and South America so it should be pretty quick to add.

Here's the link on AWS if you want to check it out https://registry.opendata.aws/noaa-rap/
