### ISSUE TITLE
Issue with filtering hourly data using Unix timestamp

### ISSUE THREAD

**Issue by kareemfcih** [alexander0042/pirateweather#39]
Hello there,

I've noticed that the PirateWeather API doesn't filter hourly data properly when a Unix timestamp is passed for a specific day. For instance, when I try to get hourly data for a specific day using the following endpoint:

[https://api.pirateweather.net/forecast/{API_KEY}/28.906433,28.232497,1680008100?lang=en&units=si](https://api.pirateweather.net/forecast/%7BAPI_KEY%7D/28.906433,28.232497,1680008100?lang=en&units=si)

It returns 48 hours of data, instead of the expected 24 hours for that specific day. In contrast, the same request made to the DarkSky API works as expected, returning 24 hours of data.

[https://api.darksky.net/forecast/{API_KEY}/28.906433,28.232497,1680008100?lang=en&units=si](https://api.darksky.net/forecast/%7BAPI_KEY%7D/28.906433,28.232497,1680008100?lang=en&units=si)

Thank you.

**Comment by henryeticom** [comment]
Exactly, is it possible you look at this please?
