### ISSUE TITLE
Discrepancy between tier cost/rewards

### ISSUE THREAD

**Issue by mbomb007** [alexander0042/pirateweather#40]
On https://pirateweather.net/en/latest/, it says 

> a $2 monthly donation lets me raise your API limit from 10,000 calls/ month to 25,000 calls per month.

On https://github.com/sponsors/alexander0042/, it says:

> **$1 a month**
>
> This helps support this project, and will let me raise your API limit from 20,000 calls per month to 50,000 calls per month!

**Comment by alexander0042** [comment]
Oops, that is an issue! When engineers try to handle pricing, the result is chaos. This is a result of me trying to dial in what it costs running this, and set up levels to roughly match my costs.

I'm going to send around an e-mail clarifying this at some point, but the web link is correct, and I'm going to update the GitHub details shortly. Anyone on the old plans will be grandfathered in though, so no concerns there!
