### ISSUE TITLE
Difference between this and OpenWeather API, your future goals?

### ISSUE THREAD

**Issue by mbomb007** [alexander0042/pirateweather#42]
## Background

I'm wondering what are the differences between this and the OpenWeather API? I use the [API 2.5](https://openweathermap.org/api/one-call-api), which was mostly compatible with Dark Sky and limits the calls. They also have a newer [API 3.0](https://openweathermap.org/api), which requires you to enter payment information even for the free plan. They will charge you if you go over your call limit, rather than returning a "limit reached" response. They also don't tell you how many requests you have left before hitting your limit.

## Questions

1. Dark Sky returned a header in the response that tells users how many requests they have left. Does this API do that? 
1. Do you require payment info for the free plan and charge for going over, or do you limit the requests? 
1. Is there a per-minute rate limit to prevent a massive amount of rapid calls?
1. Do you plan to change the API or plans offered in a future version similar to what OpenWeather did, or do you plan to keep it the same as a stand-in for Dark Sky?
1. Do you plan to create and have a weather website available, like darksky.net used to be?
1. Fun question, do you support or plan to support [emoji weather maps](https://googlemapsmania.blogspot.com/2017/07/the-emoji-weather-map.html), like Dark Sky had?

**Comment by cloneofghosts** [comment]
I only have access to the old portal so I'm not sure if anything has changed since the transition to Apiable but I do think that this information should be on the pricing page. It also doesn't tell you how many calls you get either which I find odd.

I'm not 100% on this but I think once you've exhausted your calls the API will return an error code but @alexander0042 knows for sure. The old portal says Requests limited to 100 per second, and 1000 in a burst. but no idea if that has changed.

The front-end website is available at https://merrysky.net

**Comment by tannewt** [comment]
I just signed up for a free plan and didn't enter any payment info.

**Comment by alexander0042** [comment]
Great questions, and apologies for my slow reply here! I'm usually pretty quick at getting to these, but in the deluge after Dark Sky shut down I just got overwhelmed by quantity, so working though stuff now. I've copied and pasted your questions here, so with my answers below them:

- Dark Sky returned a header in the response that tells users how many requests they have left. Does this API do that?
    - Not yet, but soon! I'm switching over to a new back-end that will provide that in the next couple weeks! It'll work exactly the same way Dark Sky did, so nice solution. 
- Do you require payment info for the free plan and charge for going over, or do you limit the requests?
    - I'm hoping to set something like that up longer term, but for now it's just the quota limits.
- Is there a per-minute rate limit to prevent a massive amount of rapid calls?
    - Yes, but it's pretty high. Since everything is built using AWS Serverless tools, it scales really well, so while I have a limiter, it's set at 1000 calls/ minute.
- Do you plan to change the API or plans offered in a future version similar to what OpenWeather did, or do you plan to keep it the same as a stand-in for Dark Sky?
    - Maybe some day! The next steps are on the [roadmap](http://pirateweather.net/en/latest/roadmap/), and so text summaries are better short term historic data is first. If I added another format, it would probably be Apple Weather.
- Do you plan to create and have a weather website available, like darksky.net used to be?
    - Yes! It's not run by me, but I work with the dev on [merrysky.net/](https://merrysky.net/)! Uses Pirate Weather as a data provider, and set up using a similar style.
- Fun question, do you support or plan to support [emoji weather maps](https://googlemapsmania.blogspot.com/2017/07/the-emoji-weather-map.html), like Dark Sky had?
    - This was great, but alas, I need to get maps working first, and that's another big lift!

Hope this helps, and again, sorry for the slow reply here

**Comment by alexander0042** [comment]
I guess I should clarify this in the docs, but for the free level you shouldn't need to enter any payment information. It just asks for name/ e-mail, and will cut off after 10,000 requests/ month, but doesn't require any sort of card confirmation!
