### ISSUE TITLE
Bug: Invalid times in timemachine response

### ISSUE THREAD

**Issue by bakobako** [alexander0042/pirateweather#46]
Hey, I have been playing around with the API and i found something i think might be a bug : 

When calling : 

`curl --location 'https://timemachine.pirateweather.net/forecast/API_TOKEN/50.0,14.43,1609452000?units=si'`

I get the following daily data : 

```
"daily": {
        "data": [
            {
                "time": 1609369200,
                "icon": "clear-day",
                "summary": "Clear",
                "sunriseTime": 1609444732,
                "sunsetTime": 1609474091,
                "moonPhase": 0.55,
                "precipAccumulation": 0.01,
                "precipType": "none",
                "temperatureHigh": 4.23,
                "temperatureHighTime": 1609419600,
                "temperatureLow": -1.96,
                "temperatureLowTime": 1609448400,
                "apparentTemperatureHigh": 2.77,
                "apparentTemperatureHighTime": 1609419600,
                "apparentTemperatureLow": -4.85,
                "apparentTemperatureLowTime": -4,
                "dewPoint": -2.43,
                "pressure": 968.97,
                "windSpeed": 1.97,
                "windBearing": 169.89,
                "cloudCover": 0.14,
                "temperatureMin": -1.96,
                "temperatureMinTime": 1609448400,
                "temperatureMax": 4.23,
                "temperatureMaxTime": 1609419600,
                "apparentTemperatureMin": -4.85,
                "apparentTemperatureMinTime": -4,
                "apparentTemperatureMax": 2.77,
                "apparentTemperatureMaxTime": 1609419600
            }
        ]
    }
```
The apparentTemperatureMinTime , apparentTemperatureLowTime are incorrect right?  or am i misunderstanding that they should be UNIX timestamps?

**Comment by alexander0042** [comment]
Hi, 

Sorry about this- it’s 100% a bug I introduced while trying to fix something else! I’ve tagged it for fixing, and should have it corrected by early next week. 

Thanks for bringing this to my attention!

**Comment by alexander0042** [comment]
Sorry for the radio silence here! I ended up fixing this shortly after, but completely forgot to update the issue.

Since this should be addressed, I'm going to close, but absolutely let me know if I've missed anything or if there are any other issues, and thanks again for using this service!
