### ISSUE TITLE
Sorry.. the Pirateweather forecast is not available.

### ISSUE THREAD

**Issue by Valley8140** [alexander0042/pirateweather#47]
Hi, I'm running Pw within a WordPress site. Pw files have been uploaded and edited using a WordPress plugin "Advanced file manager" which is a bit like a Cpanel utility. I've run into 2 issues.

- I've changed the list of towns but it doesn't show on the website; it still shows the default list
- the above message ("Sorry.. the Pirateweather forecast is not available.") has now been showing. Is this a cache related issue (as maybe the first issue is?)

**Comment by Valley8140** [comment]
Sorry this is regarding the stand alone application found at saratoga-weather.org

**Comment by alexander0042** [comment]
Thanks for clarifying the issue here! It sounds like you've got it sorted out, so I'm going to close for now, but let me know if anything else comes up
