### ISSUE TITLE
Incorrect timezone and offset to Lisbon, Portugal

### ISSUE THREAD

**Issue by jgrahamc** [alexander0042/pirateweather#51]
Get this from the API:

   "latitude" : 38.729,
   "longitude" : -9.153,
   "offset" : -1,
   "timezone" : "Etc/GMT+1"

The timezone is sort of correct (but would be better as Europe/Lisbon) but the offset is wrong. It should be +1.

**Comment by jgrahamc** [comment]
Yes. Thanks. I switched to `tz=precise` and it works perfectly. I'm only querying once every 30 minutes so the extra 1/5s doesn't matter. Cheers. Great project.

**Comment by alexander0042** [comment]
Thanks for the quick follow-up here! I'm going to close this for now, but definitely feel free to re-open if anything else comes up
