### ISSUE TITLE
The specified key does not exist - but it does

### ISSUE THREAD

**Issue by neilkplugins** [alexander0042/pirateweather#58]
I am getting the following response (and a number of other users are seeing the same issue on the Indigo Domotics forum.

content-encoding: br
content-type: text/html
date: Sat, 22 Apr 2023 15:47:08 GMT
etag: W/"5f3cc4105afcad5b5e05f15c15aeaeb2"
last-modified: Wed, 19 Apr 2023 12:30:30 GMT
server: AmazonS3
vary: Accept-Encoding
via: 1.1 dfd34e1e01b522d0fbbf77a5352081ce.cloudfront.net (CloudFront)
x-amz-cf-id: m8_K_h3UqVswyKFlK0hhLveFWZhy-GEW4khFp71JS7RfXXXXXXXXXXX==
x-amz-cf-pop: ATL58-P4
x-amz-error-code: NoSuchKey
x-amz-error-detail-key: forecast/CCcJDyXCTJaSBzcmq5bC47oJuaor1kuXXXXXXXXXXX/1000
x-amz-error-message: The specified key does not exist.
x-cache: Error from cloudfront

with a freshly generated API key, two of us are in the UK if that is a difference.

**Comment by cloneofghosts** [comment]
I tried creating a key on my end and it worked without issues. It takes some time for the API key to activate so have you tried since the initial signup to see if it's started working? If it still isn't working then reach out to the developer at api@alexanderrey,ca and he can help troubleshoot the issue.

**Comment by alexander0042** [comment]
The reply from Clone of Ghosts is 100% here- for key related issues, best best is to e-mail me an we can go from there. 

I'm going to close this issue for now since there hasn't been any activity on it, but feel free to create a new one or re-open if anything else comes up!
