### ISSUE TITLE
Automatic invoice generation

### ISSUE THREAD

**Issue by rwrx** [alexander0042/pirateweather#59]
It would be really great if there will be automatically generated invoices for subscription payments. We do need invoice for every payment. I think that it will also attract other businesses to use Pirate Weather.

**Comment by alexander0042** [comment]
Hi,

Thank you for subscribing- I love hearing from people who are able to use this service, and it helps to keep the free tier available!

This is a really important issue, and something that I'm actively working on. I've had a couple other people ask me about this, and for now, if you send me an email to api@alexanderrey.ca, I'll add you to the list! 

Hopefully it's a quick fix for Apiable and I can get this corrected soon. Again, thanks for using this service, and appreciate your patience.

**Comment by alexander0042** [comment]
Since I'm adding this to my list of things (discussion #60 ) to run by the Apiable developers, I'm going to close this issue for now to centralize things there. I don't have an answer yet, but it's the top issue on that front at the moment and we're actively working on it!
