### ISSUE TITLE
site no longer working

### ISSUE THREAD

**Issue by rss81** [alexander0042/pirateweather#64]
I was accessing everything fine with the following:

https://api.pirateweather.net/forecast/yT1K6HaXkkaU6XTBJcOUo8HjcXb151Ax722mgP3t/42.338,-70.953?exclude=currently,minutely,daily,alerts&tz=precise&extend=hourly&units=us

for some reason this is no longer working.  Says internal server error?  What's up?

**Comment by AD-Wright** [comment]
[Status page](https://stats.uptimerobot.com/DRKqBCok2N) has been showing things dropping offline on and off for most of the day.  Given that it's Saturday, I'm guessing @alexander0042 tried something new, it borked, and they've been trying to get it back online?

**Comment by cloneofghosts** [comment]
Looking at the status page things have been fully online since 11:34 am GMT.

In the future if you're going to post your API call URL I'd recommend removing your private API key from the URL but since it's already posted publicly I'd recommend regenerating your API key.

**Comment by alexander0042** [comment]
Really sorry about this! I made a switch in the back end networking to use multiple availability zones (which will help long term), but broke something in the process and didn't catch it. I've corrected it now and added a test to make sure it doesn't happen again! Apologies for the issue, and thank you again for your patience here.
