### ISSUE TITLE
Pirate Weather is ignoring negative latitude (and probably also longitude)

### ISSUE THREAD

**Issue by 12932** [alexander0042/pirateweather#67]
In my query I have a negative latitude value

https://api.pirateweather.net/forecast/xyz/-31.953512,115.857048?units=ca

But pirate weather seems to be parsing it as positive, leading to incorrect location weather
```
{
    "latitude": 31.953512,
    "longitude": 115.857048,
    "timezone": "Asia/Shanghai",
    "offset": 8.0,
    "elevation": 51,
    "currently": {
        "time": 1685163120,
        "summary": "Rain",
        "icon": "rain",
        "nearestStormDistance": 0,
        "nearestStormBearing": 0,
        "precipIntensity": 1.25,
        "precipProbability": 0.9,
        "precipIntensityError": 0.56,
        "precipType": "rain",
        "temperature": 32.08,
        "apparentTemperature": 41.56,
        "dewPoint": 22.17,
        "humidity": 0.56,
        "pressure": 996.79,
        "windSpeed": 9.655,
        "windGust": 13.98,
        "windBearing": 197.43,
        "cloudCover": 1,
        "uvIndex": 8.32,
        "visibility": 16.09,
        "ozone": 283.94
    }
    
```

It is definitely not 32 degrees celsius here, the timezone is definitely not Asia/Shanghai. I'm expecting the timezone to say Australia/Perth, and the 
temperature should be about 19 degrees celcius as of now (2023-05-27T12:55:15+08:00)

**Comment by GSLaaitie** [comment]
Same problem here in South Africa.
Got a huge shock when my speaker told me to expect 31deg for today!

**Comment by alexander0042** [comment]
Shoot, sorry about this- this was a parsing error introduced with the new back-end. I've isolated what's wrong, and working on a fix now!

**Comment by alexander0042** [comment]
Ok, fix is live! Last steps are updating the changelog (v1.5.1) and deploying to time machine, but the main API should be working.

Again, apologies for the issues here, and thanks for the quick report!

**Comment by 12932** [comment]
Yep looks like its working again, thanks

**Comment by GSLaaitie** [comment]
Thanks for the quick fix!
