### ISSUE TITLE
Got "could not JSON decode Lambda function response" error when using time machine for certain locations

### ISSUE THREAD

**Issue by hengwang322** [alexander0042/pirateweather#74]
When trying to make the following call (the location is Adelaide, South Australia, the time is 2023-01-01 00:00:00):

`https://timemachine.pirateweather.net/forecast/[APIKEY]/-34.928,138.60,1672531200`

I get the following response:
```
{
  "message": "Bad Gateway",
  "error": "could not JSON decode Lambda function response: statusCode validation failed"
}
```

After some messing around, I found that it seems only locations with half hour timezone will cause this issue, such as Darwin, Australia (-12.463,130.844), New Delhi, India (28.613,77.209), St. John's, Canada (47.555,-52.745). Maybe the odd timezone is causing the issue.

**Comment by alexander0042** [comment]
Thanks for finding this- it's definitely a bug, and specific to the historic data side of things. I'll dig into it and let you know what I find

**Comment by LingLing42** [comment]
Hello, 

I'm trying to get weather data for some (3) locations, but I get the same response:
`{
  "message": "Bad Gateway",
  "error": "could not JSON decode Lambda function response: statusCode validation failed"
}`

This issue begins with 2023-11-01 00:00:00 until today. I also tested it with creators example, still the same response(s).
example link: 

`https://timemachine.pirateweather.net/forecast/[API-key]/52.54781505900733,13.342027465679983,1698793200?lang=de&units=si`
