### ISSUE TITLE
error: could not JSON decode Lambda function response: statusCode validation failed

### ISSUE THREAD

**Issue by SavageChigga** [alexander0042/pirateweather#82]
When I sent the request with some certain coordinates like [139.7313,35.7213], it will return: {"message":"Bad Gateway","error":"could not JSON decode Lambda function response: statusCode validation failed"}
the request is like "https://api.pirateweather.net/forecast/my-api-key/139.7313547065967,35.72139514775424"
but when using the coordinate in the API Docs like "https://api.pirateweather.net/forecast/my-api-key/45.42,-74.30", it can get the correct result.
I don't know if there are coordinates in some specific areas that are not supported?

**Comment by alexander0042** [comment]
Hi, thanks for opening this issue, and apologies for the problem!

I'm guessing the issue here is that you're putting in the request as <Longitude. Latitude>, when it should be <Latitude, Longitude>. I should clarify this more in the docs, and maybe come up with a better error message as well.

**Comment by wwhite74** [comment]
actually, I think I shortened and removed the space at the same time, long number works fine
