### ISSUE TITLE
No API Key from official Website

### ISSUE THREAD

**Issue by lollo78** [alexander0042/pirateweather#84]
Hi, after sign up on https://pirate-weather.apiable.io/, confirmed, login and hit on Subscribe buttons, there is no way to generate API key.
It's me or what?
Thanks for all
Bye

**Comment by lollo78** [comment]
Solved using Android phone and a mobile data connection.

**Comment by alexander0042** [comment]
Hi, happy you got this working! It's a super weird and intermittent DNS issue on Apiable's side that they should get sorted out shortly, but definitely irritating in the meantime
