### ISSUE TITLE
"error": "could not JSON decode Lambda function response: statusCode validation failed"

### ISSUE THREAD

**Issue by pixeljuggle** [alexander0042/pirateweather#86]
When making the following request:

`https://timemachine.pirateweather.net/forecast/[API_KEY]/53.35,-2.27,1682938800?exclude=currently,flags,daily`

I get the following error:
```
{
    "message": "Bad Gateway",
    "error": "could not JSON decode Lambda function response: statusCode validation failed"
}
```

I get this error with every request I try that has a negative longitude.

**Comment by alexander0042** [comment]
Thanks for opening the issue, and apologies for the bug here! It has to do with the timing of a day that rolls over into the next month, but working on a fix now

**Comment by pixeljuggle** [comment]
I can confirm this is working now. Thank you for the quick response, it very much appreciated 👍
