### ISSUE TITLE
Hourly Forecast Temps Wonky

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#9]
This is something I noticed last night and I'm seeing it again tonight. I'm assuming that this is an HRRR issue and not a pirateweather issue and if so then feel free to close. 

Anyway I've noticed that the hourly temps seem to fluctuate overnight for seemingly no reason. Here's what pirateweather is showing for my location currently:

![Screenshot_20221118-210303_DuckDuckGo](https://user-images.githubusercontent.com/10248058/202829591-02e96230-61d3-4100-9ef5-779524f2302d.jpg)

Here's Environment Canada's hourly forecast for comparison:

![Screenshot_20221118-205821_DuckDuckGo](https://user-images.githubusercontent.com/10248058/202829789-07714915-9451-409b-8d35-380b3c19acf3.jpg)

Not shown in the screenshot was HRRR forecasting a temp of -7 at 8pm. No idea why it's saying that 11pm is going to be the coolest part of the night when usually around 6am is the coldest part of the night.

**Comment by cloneofghosts** [comment]
Definitely was a HRRR issue as now everything looks normal now.

**Comment by cloneofghosts** [comment]
Since I'm pretty confident that this was a HRRR issue and not a PW issue since the issue seemed to solve itself last night I'm going to close this topic. There's not much you can do on your end to fix the issue outside of adding in NBM which isn't the priority at the moment.

**Comment by alexander0042** [comment]
Even though your gut feel here was right (it was an HRRR issue), thanks for opening this issue! It's always helpful to keep track of issues and limitations with HRRR to see where it's doing well and where it needs work. NBM is still on tap for the new year, so I haven't forgotten about it ☀️

**Comment by cloneofghosts** [comment]
It seems to have at least sorted itself out better the last few days so it's not as bad as the example I showed last week. I know HRRR is being replaced by RRFS sometime next year so maybe that will be any better? It has a NA 3km domain which is similar to the domain offered by RAP so that'll be nice.

**Comment by cloneofghosts** [comment]
I know I've brought this up before but one thing HRRR struggles at times is precipitation. I haven't found a global source of radar but the closest thing I could find is this API from [RainViewer](https://www.rainviewer.com/api.html). The only downside is that everything is in image files and you'd have to do a bunch of conversions in order to get it to be in a usable file format.

[This from EUMETSTAT](https://data.eumetsat.int/product-navigator/product/EO:EUM:DAT:0025) while not global might still be useful to cover areas outside of NA which aren't covered by RainViewer?
