### ISSUE TITLE
Possible values for alert "severity"?

### ISSUE THREAD

**Issue by dustinbolton** [alexander0042/pirateweather#90]
Hello, could you please clarify what the possible values could be for the `severity` field inside alerts?

The [Alerts>severity API documentation](https://docs.pirateweather.net/en/latest/API/#severity) does not provide details and I'd like to use this for applying different colors to alerts to differentiate them.

So far I've only seen the severity value "Moderate".

**Comment by alexander0042** [comment]
Great point, I'd missed fleshing out that part of the docs! The NWS uses the "CAP" protocol, so the official definition is on page 17 of [this document](https://www.oasis-open.org/committees/download.php/14759/emergency-CAPv1.1.pdf). 

Long story short, the categories are:
- "Extreme” - Extraordinary threat to life or property
- “Severe” - Significant threat to life or property
- “Moderate” - Possible threat to life or property
- “Minor” - Minimal threat to life or property
- “Unknown
