### ISSUE TITLE
Current weather's "nearestStormDistance" stuck at "0"

### ISSUE THREAD

**Issue by dustinbolton** [alexander0042/pirateweather#91]
I've yet to see the current weather's `nearestStormDistance` value change from zero despite several storms of varying intensity approaching and hitting my location, some very severe. I'm not fully sure if the bearing has been working though I _think_ I've only seen it as zero as well.

It seems like this feature is currently not functioning properly, at least for my area (central USA).

**Comment by alexander0042** [comment]
Hi, thanks for using this API, and apologies for the issue here!

This is something that's currently in progress, and you can follow along with issue #6 for updates.
