### ISSUE TITLE
PirateWeather API Down

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#94]
Looks like both forecast endpoints are down this morning which is confirmed by the [status page](https://stats.uptimerobot.com/DRKqBCok2N)

Trying to visit the testing endpoint gives the following error:

```
{
  "error": "could not JSON decode Lambda function response: statusCode validation failed",
  "message": "Bad Gateway"
}
```

The live endpoint is giving this error message and I was getting a ERR_EMPTY_RESPONSE error earlier

```
{
  "message": "Internal Server Error"
}
```

EDIT: I'm now getting a Service Unavailable message instead of the Internal Server Error message.

**Comment by cloneofghosts** [comment]
Can confirm that everything is back up. It switched to V1.4.1 on the live endpoint for a bit but we're good now.

**Comment by cloneofghosts** [comment]
@alexander0042 Seems to have gone down again today.

**Comment by alexander0042** [comment]
We’re on the same page here! Should be back up now.

Apologies for this again- the fix this time should be permanent!


On Aug 11, 2023, at 19:45, Kev ***@***.***> wrote:

﻿

@alexander0042<https://github.com/alexander0042> Seems to have gone down again today.

**Comment by cloneofghosts** [comment]
Can confirm everything is back up and running.
