### ISSUE TITLE
Unable to login with new account.

### ISSUE THREAD

**Issue by akballow** [alexander0042/pirateweather#96]
I tried with two emails and It always fails on login to get the API key. AM I mad, or is something wrong

**Comment by alexander0042** [comment]
Nope, not crazy, and an ongoing issue that will hopefully be fixed soon! For some small number of people. there's a weird DNS glitch that creates this problem, and Apiable is working on a fix (aka a whole new portal).

In the meantime, if you send me an e-mail to api@alexanderrey.ca, I'd be happy to generate you a key by hand.

Sorry about this,
Alexander

**Comment by akballow** [comment]
Thanks for the reply the account finally worked, it all worked perfect on HA for 1 day and now I get the following issue. 

 https://github.com/alexander0042/pirate-weather-ha/issues/134

**Comment by alexander0042** [comment]
Apologies for missing this one, and happy this particular issue was fixed! I'm going to close for now so we can focus on the HA side of things
