### ISSUE TITLE
Legacy Key Cannot Access Time Machine Data

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirateweather#98]
As I was doing some miscellaneous updates to the API docs in #97 I noticed that my legacy key cannot consume the Time Machine endpoint.

If I look at the old portal it shows that I am subscribed to the Time Machine endpoint
![image](https://github.com/alexander0042/pirateweather/assets/10248058/c0774a41-0db2-4d8f-a535-96ad680271da)

When I try to query the Time Machine endpoint I get

### Kong Error
You cannot consume this service.

It was working before the migration so I wonder if that broke anything with the older API keys?

**Comment by alexander0042** [comment]
That shouldn't happen! Just tried something, do you mind testing it again?

**Comment by cloneofghosts** [comment]
Just tested again and got the same error.

**Comment by alexander0042** [comment]
Appreciate the patience- there was an extra space in one of the Access Control Lists, which is what broke this
